# Generated by Django 5.1.4 on 2026-02-24 13:44

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Отчество')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('passport_series', models.CharField(blank=True, default='', max_length=10, verbose_name='Серия паспорта')),
                ('passport_number', models.CharField(blank=True, default='', max_length=10, verbose_name='Номер паспорта')),
                ('passport_issue_date', models.DateField(blank=True, null=True, verbose_name='Дата выдачи')),
                ('passport_issued_by', models.CharField(blank=True, default='', max_length=255, verbose_name='Кем выдан')),
                ('passport_code', models.CharField(blank=True, default='', max_length=20, verbose_name='Код подразделения')),
                ('address_region', models.CharField(blank=True, default='', max_length=255, verbose_name='Область')),
                ('address_city', models.CharField(blank=True, default='', max_length=255, verbose_name='Населённый пункт')),
                ('address_street', models.CharField(blank=True, default='', max_length=255, verbose_name='Улица')),
                ('address_house', models.CharField(blank=True, default='', max_length=20, verbose_name='Дом')),
                ('address_building', models.CharField(blank=True, default='', max_length=20, verbose_name='Корпус')),
                ('address_flat', models.CharField(blank=True, default='', max_length=20, verbose_name='Квартира')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'db_table': 'employees',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'db_table': 'organizations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
                'db_table': 'positions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('middle_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Отчество')),
                ('role', models.CharField(choices=[('admin', 'Администратор'), ('hr_manager', 'Менеджер по персоналу')], default='hr_manager', max_length=20, verbose_name='Роль')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'users',
                'ordering': ['last_name', 'first_name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('object_type', models.CharField(choices=[('organization', 'Организация'), ('department', 'Отдел'), ('position', 'Должность'), ('employee', 'Сотрудник'), ('hr_operation', 'Кадровая операция')], max_length=20, verbose_name='Тип объекта')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID объекта')),
                ('changed_fields', models.JSONField(default=list, verbose_name='Изменённые поля')),
                ('old_values', models.JSONField(default=dict, verbose_name='Старые значения')),
                ('new_values', models.JSONField(default=dict, verbose_name='Новые значения')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_history', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
            ],
            options={
                'verbose_name': 'Запись истории',
                'verbose_name_plural': 'История изменений',
                'db_table': 'change_history',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.department', verbose_name='Родительский отдел')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='core.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
                'db_table': 'departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('file', models.FileField(upload_to='employee_files/%Y/%m/', verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
                'db_table': 'files',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='HrOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('hire', 'Принятие на работу'), ('salary_change', 'Изменение зарплаты'), ('department_change', 'Изменение отдела'), ('dismissal', 'Увольнение')], max_length=20, verbose_name='Тип операции')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Зарплата')),
                ('effective_date', models.DateField(verbose_name='Дата вступления в силу')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_operations', to=settings.AUTH_USER_MODEL, verbose_name='Кем создано')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_operations', to='core.department', verbose_name='Отдел')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_operations', to='core.employee', verbose_name='Сотрудник')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_operations', to='core.position', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Кадровая операция',
                'verbose_name_plural': 'Кадровые операции',
                'db_table': 'hr_operations',
                'ordering': ['-effective_date'],
            },
        ),
    ]
